import fs from 'fs';
import path from 'path';
import PDFDocument from 'pdfkit';
import { fileURLToPath } from 'url';
import { env } from '../config/env.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const pdfDir = path.resolve(__dirname, '../storage/pdfs');

function sanitizeFilename(value) {
  return String(value).replace(/[^a-z0-9-_]+/gi, '-').replace(/-+/g, '-').toLowerCase();
}

function ensurePdfDir() {
  fs.mkdirSync(pdfDir, { recursive: true });
}

function writePdf(filename, build) {
  ensurePdfDir();
  const safeName = sanitizeFilename(filename);
  const outputPath = path.join(pdfDir, `${safeName}.pdf`);
  const doc = new PDFDocument({ margin: 48 });
  doc.pipe(fs.createWriteStream(outputPath));
  build(doc);
  doc.end();
  return `${env.pdfBaseUrl}/${safeName}.pdf`;
}

export function generateInvoicePdf(invoice, customer) {
  return writePdf(`invoice-${invoice.id}`, (doc) => {
    doc.fontSize(20).text('NxtBiz Invoice');
    doc.moveDown();
    doc.fontSize(12).text(`Invoice ID: ${invoice.id}`);
    doc.text(`Customer: ${customer?.name || 'Unknown customer'}`);
    doc.text(`Due date: ${new Date(invoice.dueDate).toLocaleDateString()}`);
    doc.text(`Amount due: ${invoice.amount}`);
    doc.moveDown();
    doc.text('Generated by NxtBiz operations automation.');
  });
}

export function generateReportPdf(report) {
  return writePdf(`report-${report.id}-${report.title}`, (doc) => {
    doc.fontSize(20).text(report.title);
    doc.moveDown();
    doc.fontSize(12).text(report.summary || 'NxtBiz operations report');
    doc.moveDown();
    doc.text('Metrics');
    Object.entries(report.metrics || {}).forEach(([key, value]) => doc.text(`${key}: ${value}`));
    doc.moveDown();
    doc.text('Recommendations');
    (report.recommendations || []).forEach((item) => doc.text(`- ${item}`));
  });
}
